blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/yigitbozyaka/knack/discussions
    about: For open-ended questions, ideas, or discussion. Please don't open issues for these.
